version: '3.0'

services:
  db:
    container_name: 'ours-main-db'
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: root
      POSTGRES_DB: test
    ports:
      - "5434:5432"
    networks:
      transcoding-app:
        aliases:
          - db

  migrate:
    container_name: 'ours-main-migrate'
    image: migrate/migrate
    command: ["-path=/migrations/", "-database", "postgres://root:test@db:5432/test?sslmode=disable", "up"]
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    networks:
      transcoding-app:

networks:
  transcoding-app:
    external: true